/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["AppController_getHello"];
  };
  "/v1/cef-connect/daily-prices": {
    get: operations["CefConnectV1Controller_dailyPrices"];
  };
  "/v1/cef-connect/custom-daily-prices": {
    get: operations["CefConnectV1Controller_customDailyPrices"];
  };
  "/v1/cef-connect/symbols": {
    get: operations["CefConnectV1Controller_getStockTickers"];
  };
}

export interface components {
  schemas: {
    CEFDailyPrice: {
      Ticker: string;
      Discount: number;
      DistributionRateNAV: number;
      DistributionRatePrice: number;
      DistributionAmtUSD: number;
      ReturnOnNAV: number;
      CategoryId: number;
      CategoryName: string;
      SponsorId: number;
      SponsorName: string;
      IsManagedDistribution: boolean;
      Price: number;
      PriceChange: number;
      NAV: number;
      NAVPublished: string;
      Cusip: string;
      Name: string;
      LastUpdated: string;
      NavTicker: string;
      Strategy: string;
      LeverageRatioPercentage: number;
      MarketCapUSDm: number;
      UNIIPerShare: number;
      DistributionFrequency: string;
      EarningsPerShare: number;
      CurrentDistribution: number;
      InceptionPrice: number;
      AverageCoupon: number;
      AMTPercentage: number;
      AverageWeightedMaturity: number;
      ExpenseRatio: number;
      BaselineExpense: { [key: string]: unknown };
      TotalAssetsUSDm: number;
      IsLeveraged: boolean;
      IsPriceBelow52WkAvg: boolean;
      IsDiscountBelow52WkAvg: boolean;
      IsAMTPct: boolean;
      IsManaged: boolean;
      Term: boolean;
      AvgWtdDurationLevAdj: number;
      Yr3RetOnNav: number;
      Yr3RetOnPrice: number;
      Yr5RetOnNav: number;
      Yr5RetOnPrice: number;
      YTDRetOnNav: number;
      YTDRetOnPrice: number;
      SinceInceptionRetOnNav: number;
      SinceInceptionRetOnPrice: number;
      ReturnOnPrice: number;
      AvgDailyVolume: number;
      CallableYr1Pct: number;
      PrerefundedPercentage: number;
      AvgBondPrice: number;
      AvgWtdDurationNonLevAdj: number;
      EffDurationLevAdj: number;
      EffDurationNonLevAdj: number;
      Price52WkAvg: number;
      Discount52WkAvg: number;
      ZScore1Yr: number;
      ZScore3M: number;
      ZScore6M: number;
      ZScoreDate: string;
      InceptionDate: string;
      InceptionDateString: string;
      InceptionDateUnixTimestamp: number;
      DistributionDate: string;
    };
    CustomCEFDailyPrice: {
      Ticker: string;
      Discount: number;
      DistributionRateNAV: number;
      DistributionRatePrice: number;
      DistributionAmtUSD: number;
      ReturnOnNAV: number;
      CategoryId: number;
      CategoryName: string;
      SponsorId: number;
      SponsorName: string;
      IsManagedDistribution: boolean;
      Price: number;
      PriceChange: number;
      NAV: number;
      NAVPublished: string;
      Cusip: string;
      Name: string;
      LastUpdated: string;
      NavTicker: string;
      Strategy: string;
      LeverageRatioPercentage: number;
      MarketCapUSDm: number;
      UNIIPerShare: number;
      DistributionFrequency: string;
      EarningsPerShare: number;
      CurrentDistribution: number;
      InceptionPrice: number;
      AverageCoupon: number;
      AMTPercentage: number;
      AverageWeightedMaturity: number;
      ExpenseRatio: number;
      BaselineExpense: { [key: string]: unknown };
      TotalAssetsUSDm: number;
      IsLeveraged: boolean;
      IsPriceBelow52WkAvg: boolean;
      IsDiscountBelow52WkAvg: boolean;
      IsAMTPct: boolean;
      IsManaged: boolean;
      Term: boolean;
      AvgWtdDurationLevAdj: number;
      Yr3RetOnNav: number;
      Yr3RetOnPrice: number;
      Yr5RetOnNav: number;
      Yr5RetOnPrice: number;
      YTDRetOnNav: number;
      YTDRetOnPrice: number;
      SinceInceptionRetOnNav: number;
      SinceInceptionRetOnPrice: number;
      ReturnOnPrice: number;
      AvgDailyVolume: number;
      CallableYr1Pct: number;
      PrerefundedPercentage: number;
      AvgBondPrice: number;
      AvgWtdDurationNonLevAdj: number;
      EffDurationLevAdj: number;
      EffDurationNonLevAdj: number;
      Price52WkAvg: number;
      Discount52WkAvg: number;
      ZScore1Yr: number;
      ZScore3M: number;
      ZScore6M: number;
      ZScoreDate: string;
      InceptionDate: string;
      InceptionDateString: string;
      InceptionDateUnixTimestamp: number;
      DistributionDate: string;
      EstimatedIncome: number;
      NumberOfSharesPerOneDollarInvested: number;
      AnnualIncomePerOneDollarInvested: number;
      AnnualIncomePerOneHundredDollarsInvested: number;
      MoneyInvested: number;
      TotalIncome: number;
      CustomUpdated: string;
    };
  };
}

export interface operations {
  AppController_getHello: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  CefConnectV1Controller_dailyPrices: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CEFDailyPrice"][];
        };
      };
      500: unknown;
    };
  };
  CefConnectV1Controller_customDailyPrices: {
    parameters: {
      query: {
        /** All ticker symbols that are separated by commas (ex. ABC,DEF,GHI) to obtain CEF data for each requested ticker symbol */
        tickerSymbols?: string;
        /** Total numeric value of money invested into closed-end fund */
        moneyInvested: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CustomCEFDailyPrice"][];
        };
      };
      500: unknown;
    };
  };
  CefConnectV1Controller_getStockTickers: {
    parameters: {};
    responses: {
      /** All Ticker Symbols from the CEF Connect Daily Pricing (All closed-end funds) */
      200: {
        content: {
          "application/json": string[];
        };
      };
      500: unknown;
    };
  };
}

export interface external {}
